feat(dep): add private registry support
This removes the use of any npmjs.io API and solely relies on the
npm cli. Therefore it now works for private repo stuff.

Example output

```
$ bb dep check bower
Analyzing the package bower@latest ...
Getting dependencies...
Creating the list of 4th party deps...
/Users/standa/Dev/black-belt/list.txt
Creating the Public License field contents...
/Users/standa/Dev/black-belt/licenses.txt

bower@1.8.4
License: MIT
Copyright Notice: Copyright (c) 2013-present Twitter and other
contributors
Dependencies: 0
Elligible for Pre-Approval: True

Description: The browser package manager
Package: https://npmjs.com/package/bower
Repo: https://github.com/bower/bower
```

Missing module

```
$ bb dep check bower-nonexistent-npm
Analyzing the package bower-nonexistent-npm@latest ...
Getting dependencies...
Usage: bb dep check [OPTIONS] DEP

Error: Invalid value: The npm package could not be installed
```

Missing module version

```
$ bb dep check bower@333.33.33
Analyzing the package bower@333.33.33 ...
Getting dependencies...
Usage: bb dep check [OPTIONS] DEP

Error: Invalid value: The npm package could not be installed
```